CREATE TABLE Roles (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    emertimi VARCHAR(100) NOT NULL,
    pershkrimi TEXT,
    normalized_name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE Users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    emri VARCHAR(50) NOT NULL,
    mbiemri VARCHAR(50) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    phone_number VARCHAR(20),
    email_confirmed BOOLEAN DEFAULT FALSE,
    lockout_enabled BOOLEAN DEFAULT FALSE,
    access_failed_count INT DEFAULT 0,
    data_krijimit TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    statusi VARCHAR(20) DEFAULT 'active'
);

CREATE TABLE UserRoles (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    role_id INT UNSIGNED NOT NULL,
    UNIQUE(user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES Roles(id) ON DELETE CASCADE
);

CREATE TABLE RefreshTokens (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    token VARCHAR(500) UNIQUE NOT NULL,
    expires TIMESTAMP NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    revoked TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);